INSERT INTO BOOK (BOOK_ID,BOOK_NAME,AUTHOR,AVAILABLE_COPIES,TOTAL_COPIES)VALUES ('Book1','Camel Fundamentals','John',0, 2);
INSERT INTO BOOK (BOOK_ID,BOOK_NAME,AUTHOR,AVAILABLE_COPIES,TOTAL_COPIES)VALUES ('Book2','Maven Fundamentals','Smith', 3,3);
INSERT INTO BOOK (BOOK_ID,BOOK_NAME,AUTHOR,AVAILABLE_COPIES,TOTAL_COPIES)VALUES ('Book3','Java Fundamentals','kethe shira', 4,4);
INSERT INTO SUBSCRIPTION (SUBSCRIBER_NAME,DATE_SUBSCRIBED,DATE_RETURNED,BOOK_ID)VALUES ('Ram','2021-06-06',null, 'Book1');
INSERT INTO SUBSCRIPTION (SUBSCRIBER_NAME,DATE_SUBSCRIBED,DATE_RETURNED,BOOK_ID)VALUES ('Shyam','2021-06-07',null, 'Book1');